Add support for hidden node
bitnami/bitnami-docker-mongodb pull request #246
Opened 2021-01-25 13:44 UTC by deveshk0

**Description of the change**

This PR adds ability to add a hidden node to the cluster which can be used for analytical queries, running backups etc

**Benefits**

- Hidden node in mongodb

**Possible drawbacks**

Unknown

**Applicable issues**

Fixes https://github.com/bitnami/bitnami-docker-mongodb/issues/145

2021-01-26 11:23 UTC, deveshk0 commented
@sameersbn  @juan131 Can anyone have a look into this PR?

2021-01-26 11:35 UTC, carrodher commented
> @sameersbn @juan131 Can anyone have a look into this PR?

Thanks for the PR, our team is actively monitoring the different bitnami repositories, we are used to reviewing/answering the different issues/PRs within a business day. Please take into account we are a small team maintaining a lot of different containers and chart repositories. In fact, at this moment I was taking a look at the changes.

2021-01-26 11:43 UTC, carrodher requested changes
Some minor comments, the rest of the changes LGTM.

@rafariossaa @javsalgar can you also take a look at this PR?

2021-01-26 11:43 UTC, carrodher commented on 4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh
> +# Get if secondary node is pending
```suggestion
# Get if hidden node is pending
```

this change should be applied to the rest of branches.

2021-01-26 11:43 UTC, carrodher commented on 4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh
> +        info "Adding node to the cluster"
```suggestion
        info "Adding hidden node to the cluster"
```
At this point, I would add something to differentiate if it is a hidden node or not

2021-01-26 11:43 UTC, carrodher commented on README.md
> +### Step 4: Create a replication hidden node
Not sure if we should add here something like "Optional", in the sense that this is not necessary in all the use cases, so not sure if it should be added as a default step or an additional feature that can be used or not.

This is applicable to the documentation and the default docker-compose.

The question is should we add the hidden node as a node deployed by default or just document how it can be deployed?
cc @javsalgar @rafariossaa

2021-01-26 12:16 UTC, deveshk0 commented on README.md
> +### Step 4: Create a replication hidden node
@carrodher  Then shouldn't we do same for arbiter node also

2021-01-27 16:19 UTC, deveshk0 commented on README.md
> +### Step 4: Create a replication hidden node
@carrodher Shall I change this to optional?

2021-01-27 23:40 UTC, carrodher commented on README.md
> +### Step 4: Create a replication hidden node
IMHO it is not needed by default for all the use-cases. I'd document that feature and how to deploy it in the README but without making it the default option in the docker-composes or examples.

In the [official docs](https://docs.mongodb.com/manual/core/replica-set-members/), three members are described: primary, secondary, and arbiter; then there are other members like [hidden replica](https://docs.mongodb.com/manual/core/replica-set-hidden-member/) or [delayed replica](https://docs.mongodb.com/manual/core/replica-set-delayed-member/), but let’s say there are like another features, no "main/core" members. I think adding the hidden replica by default to the deployments is going to add complexity and I am not sure if all the users are going to be interested in using that feature.

2021-01-28 09:36 UTC, deveshk0 commented on README.md
> +### Step 4: Create a replication hidden node
Fair point @carrodher , I will document the feature and how to deploy it in the README but without making it the default option in the docker-composes or examples.

2021-01-28 10:35 UTC, deveshk0 commented on README.md
> +### Step 4: Create a replication hidden node
@carrodher It is update, Please have a look.

2021-01-28 12:59 UTC, carrodher approved these changes
LGTM, thank you very much for the contribution and the latest changes.

Before merging the changes we need to do some tests in our internal CI/CD system, if everything works as expected no action is needed on your side. If something is not working we will ping you to try to figure out what is happening (if the issue is related to the changes of course).

2021-02-01 14:33 UTC, merged

2021-02-01 14:33 UTC, carrodher commented
PR is merged! Thanks for the contribution. Now the code is present in this GH repo, it should be available in DockerHub (and the rest of registries) when a new release of the image appears.