MONGODB_ADVERTISED_PORT support for custom external port
bitnami/bitnami-docker-mongodb pull request #311
Opened 2021-12-28 17:08 UTC by deveshk0

**Description of the change**

This PR introduces `MONGODB_ADVERTISED_PORT` environment variable to cutomise port for external access.

**Benefits**

- Ability to expose on NodePort in kubernetes
- Ability to run on custom port for LoadBalancer Servcie in kubernetes

**Possible drawbacks**

NA

**Applicable issues**

https://github.com/bitnami/charts/issues/5508

**Additional information**

None

2021-12-29 11:24 UTC, marcosbc requested changes
Thanks for the contribution! In general it looks fine, but I have a couple of minor requests. Let me know if you have any concerns or questions.

2021-12-29 11:24 UTC, marcosbc commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export MONGODB_ADVERTISED_PORT="${MONGODB_ADVERTISED_PORT:-}"
For consistency with other similar variables, could you name it as `MONGODB_ADVERTISED_PORT_NUMBER`?

2021-12-29 11:24 UTC, marcosbc commented on 4.0/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh
> +########################
This comment does not have the same format as other ones, could you fix that?

2021-12-29 11:34 UTC, deveshk0 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export MONGODB_ADVERTISED_PORT="${MONGODB_ADVERTISED_PORT:-}"
Sure :)

2021-12-29 11:42 UTC, deveshk0 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export MONGODB_ADVERTISED_PORT="${MONGODB_ADVERTISED_PORT:-}"
Updated to `MONGODB_ADVERTISED_PORT_NUMBER `

2021-12-29 11:42 UTC, deveshk0 commented on 4.0/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh
> +########################
Updated comment

2022-01-03 09:13 UTC, deveshk0 commented
@marcosbc Do you need any other change on this PR?

2022-01-03 14:37 UTC, marcosbc requested changes
Thanks a lot for making the changes! And sorry for the delay, but due to winter holidays we have been at minimum capacity.

I have one additional request apart from my comments below: Could you add the environment variable in the ["Setting up replication" section in the `README.md` file](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-up-replication)?

2022-01-03 14:37 UTC, marcosbc commented on 4.2/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh
> +    port=$(get_mongo_port)
In this case, the `port` variable is not declared so it would make it a global variable, and could cause conflicts with `local -r port` used in functions. Could you declare it above? Refer to L1211 to see how `node` is declared. Note you can also do it in the same line:

```
local node port
```

2022-01-03 14:37 UTC, marcosbc commented on 4.0/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh
> +########################
For consistency with other comments, could you add the Globals and Arguments sections?

2022-01-03 15:14 UTC, deveshk0 commented on 4.2/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh
> +    port=$(get_mongo_port)
Thanks, I have changed  the variable to local

2022-01-03 15:16 UTC, deveshk0 commented on 4.0/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh
> +########################
I have added `Globals and Arguments sections` for `get_mongo_hostname` and `get_mongo_port` functions

2022-01-03 15:16 UTC, marcosbc approved these changes
Thanks for the quick turnaround! LGTM! We will merge the changes shortly.

2022-01-03 15:52 UTC, merged